### ISSUE TITLE
Detected Menu, or Nah?

### ISSUE THREAD

**Issue by LutraVibes** [504brandon/504Brandon-Mini-Cheats#2]

**Comment by KittySleeper** [comment]
no

**Comment by LutraVibes** [comment]
How sure are we tho? I saw on the Code of Conduct board, it said that there was color coding, and some of the mods were detected.

**Comment by KittySleeper** [comment]
> How sure are we tho? I saw on the Code of Conduct board, it said that there was color coding, and some of the mods were detected.

That's for if mods were detected if a mod was detected I would put that but there is currently no detected mods
